### ISSUE TITLE
Error running Windows matlab s

### ISSUE THREAD

**Issue by smdb21** [fosterlab/PrInCE-Matlab#4]
Hi, I got an error running some dataset.
After running for several hours I get this:
![image](https://user-images.githubusercontent.com/11353022/68889601-16953f00-06d2-11ea-8ecb-0b0511e08c5c.png)

And in the log file I got:

![image](https://user-images.githubusercontent.com/11353022/68889683-404e6600-06d2-11ea-8ad1-61e2478d9e74.png)

I wanted to check whether I need to update something, but I couldn't download the latest installation package for Windows.
I would appreciate any help on this.
Thanks!

**Comment by GregStacey** [comment]
We'll see if the newly-compiled Windows standalone fixes this. (I'll upload the standalone in the next couple days.)

Were you running the practice dataset or your own? If your own and the error persists, you could send me the dataset for troubleshooting. Thanks!

**Comment by GregStacey** [comment]
A new Windows standalone version is available (https://drive.google.com/file/d/1pKbna5_CCvxjzz9VFwBiIgjtqud6SeOP/view?usp=sharing, also now linked in the README). Hopefully that solves the error.

**Comment by smdb21** [comment]
I will try and let you know either way

**Comment by smdb21** [comment]
Hi!
After installing the latest version, I got this error:
![image](https://user-images.githubusercontent.com/11353022/69075828-09849280-09e7-11ea-8bd9-97c399f3367f.png)
The log file is here:
[logfile.txt](https://github.com/fosterlab/PrInCE-Matlab/files/3859893/logfile.txt)
The input files I use are in this zip:
[Input.zip](https://github.com/fosterlab/PrInCE-Matlab/files/3859903/Input.zip)
Thank you for your help!

**Comment by GregStacey** [comment]
Hi Salvador, do you have one experimental condition and three replicates? If so, your condition files might be misformatted. Each experimental condition should have its own csv file, and each of those files should have all replicates. To correctly format the files, just copy and paste from condition2.csv and condition3.csv into condition1.csv (minus the headers).

Fixing this should solve the errors. I'm confirming that's the case for you data.

(If, instead, you have three experimental conditions with one replicate each, just set the replicate column in each file to be equal to 1 on all rows.)

**Comment by GregStacey** [comment]
I confirmed that fixing your input files fixed the error (merging condition1.csv, condition2.csv, and condition3.csv). I'll close this issue, but let me know if any errors persist for you and we can reopoen or start a new issue.

**Comment by smdb21** [comment]
Ok, I am still running it. If you confirm it, that is great!
Thank you again for your help!

**Comment by smdb21** [comment]
Hi @GregStacey , sorry to bother again.
I did what you said, having just 1 condition, and 3 replicates, I convert it to just having an input file condition1.csv, with the corresponding column of replicate 1-2-3.
However, I still get an error, this one different:
![image](https://user-images.githubusercontent.com/11353022/69451079-677ce700-0d13-11ea-8ec7-2e3aac4f394c.png)
I attach log file:
[logfile.txt](https://github.com/fosterlab/PrInCE-Matlab/files/3880905/logfile.txt)
And input merged file:
[condition1.zip](https://github.com/fosterlab/PrInCE-Matlab/files/3880906/condition1.zip)
The output so far is this:
[Output.zip](https://github.com/fosterlab/PrInCE-Matlab/files/3880914/Output.zip)
(next time I try, can I skip one of the steps so that I can do it faster?).

Thanks again for the help

**Comment by GregStacey** [comment]
Hi Salvador, unfortunately I can't reproduce the error. It looks like it's not finding the Alignment module (Alignment.m). Luckily Alignment is an optional step, so you should be able to get around the error by just skipping it. (You should see a button to skip it when you start prince.) I hope that works!

**Comment by smdb21** [comment]
Hi! Thanks for trying. However, I tried to re-run it skipping the alignment module and I still get exactly the same error. 
Do you recommend me to re-install or something? Not sure why I get an error like that.
Thanks again
